### ISSUE TITLE
Finish the design

### ISSUE THREAD

**Issue by bertez** [unfoldcollective/Apprentice-of-Okolicne#10]
Please upload here all the final elements.

Deps:
- #2

**Comment by phivk** [comment]
Graphic designs are approved:
https://drive.google.com/folderview?id=0B0LkX_BiOf9xQ3pPOTNHa0pnLUE

1 element is missing: the 'fun fact' text notifications that appear in the top left corner of the canvas. the designs are as in these files:
https://benchteam.slack.com/files/mato/F6PE3RJ3F/moz_text_2-07.png
https://benchteam.slack.com/files/mato/F6Q7BP44E/text_test.mp4

There is a bit of logic involved:
- certain texts are triggered when a specific element (pattern, environment, or figure/object) is dropped on the canvas
- certain texts are generic (not related to any specific element). when in step 3 (figs/obs) no text has been triggered yet, a generic text is triggered after the 2nd element has been dropped. This ensures that every user who completes a composition will see at least 1 text notification.

**Comment by phivk** [comment]
@bertez I'm leaving this issue open for you to close when you are sure you have all designs as needed
