### ISSUE TITLE
email submit button should use checkmark icon instead of right arrow

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#101]
this is the final interaction that completes the user's creation, so the button should signify 'being done'
![screen shot 2017-09-08 at 11 03 53](https://user-images.githubusercontent.com/902958/30204393-9d4849b4-9485-11e7-8917-3cc6ab0ef9b3.png)

**Comment by bertez** [comment]
So, 
- step 1: arrow
- step 2: arrow
- step 3: checkmark
- save step 1: checkmark
- save step 2: checkmark

am I right?

**Comment by phivk** [comment]
Almost:

step 1: arrow
step 2: arrow
step 3: checkmark
save step 1: arrow
save step 2: checkmark
