### ISSUE TITLE
create1: 'next button' should become clickable immediately after pattern dropped

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#102]
![screen shot 2017-09-08 at 12 19 37](https://user-images.githubusercontent.com/902958/30207524-20679142-9490-11e7-82f0-bb450ec9594f.png)

**Comment by bertez** [comment]
The main problem about this is that even if the button is clicable inmediately the user could not click on it because of the hand animation over it. Also is a little bit of work to make the animation go away.

**Comment by phivk** [comment]
can we simply raise the hand animation so that it doesnt overlap?

**Comment by bertez** [comment]
I'll try 👍

**Comment by phivk** [comment]
has this been released? I don't see it on production...

**Comment by bertez** [comment]
No, I didn't release yet, I asked on friday if I could restart production for a few minutes because I'm not sure of the opening hours... And during the weekend I was very busy.

I'll update this evening after the exhibit is closed.
