### ISSUE TITLE
Define transitions

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#18]
define transitions:
- [X] UPDATE: between *creation* screens: keep all static elements the same, and fade in newly loaded palette elements
- [X] of input labels on Save screen (https://drive.google.com/open?id=0B0LkX_BiOf9xUUszS2pnVUJEZ2M)
- [X] hands attention-grabbing animation (https://drive.google.com/drive/folders/0B0LkX_BiOf9xOXBXZV9Ua1lxZ1E)
- [X] 'fun-fact' text notifications (https://drive.google.com/open?id=0B0LkX_BiOf9xWFhHYTlBLUQtZ1U)

Deps:
#15 

EDIT: updated link to folder with hands attention-grabbing animations

**Comment by bertez** [comment]
The 1st and 2nd videos are the same...

Where do I get the fun facts? Are they related to the "parts" or general?

TY

**Comment by phivk** [comment]
I've updated the link to the hands animations

Fun fact texts are being translated and should be ready tomorrow.
Slovak versions are final.
All of them are prepared in this gDoc: https://docs.google.com/document/d/1o_DRIBoIlfASayI4Zt9zc4vKChcYeTdEw66B38N45wA/edit?usp=sharing

they fall into 2 categories and there's a bit of logic involved:
1. specific for a particular element: triggered when a specific element (pattern, environment, or figure/object) is dropped on the canvas
2. general for a category (patterns, environments, figs/objs): triggered when an element is dropped in that category and no specific text is available.

@bertez can you use placeholder texts for now? I will fill in final + translated texts next wednesday or thursday.

**Comment by bertez** [comment]
Yes, no problem about the texts.

When does the hand animations happen?

**Comment by phivk** [comment]
@bertez see for this kind of UX (what appears when) the spec on Zeplin:
https://app.zeplin.io/project/59956ab13afdaa297f4cc186

particularly screens: 1c, 1d, 2b

**Comment by phivk** [comment]
for now skip option 2 (general)

> general for a category (patterns, environments, figs/objs): triggered when an element is dropped in that category and no specific text is available.
