### ISSUE TITLE
Font is too bold

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#19]
font is too bold (compared to design on Screen1)
Probably caused by bold font-weight on font that is already bold
Fixed by setting `font-weight: 100;`

**Comment by bertez** [comment]
Hace you tried that? Does it work?

The fonts you sent me are MaiolaBold and Maiola-BoldItalic.

**Comment by phivk** [comment]
Yes I've tried setting `font-weight: 100;`:
![screen shot 2017-08-23 at 12 01 37](https://user-images.githubusercontent.com/902958/29610599-fd6b5f1c-87fa-11e7-8974-ea510a6e4c82.png)
![screen shot 2017-08-23 at 12 01 45](https://user-images.githubusercontent.com/902958/29610603-ffe4dac0-87fa-11e7-9045-8a3245c327e1.png)

**Comment by bertez** [comment]
I do not notice any differente, I suppose it does not work. Am I wrong?

**Comment by phivk** [comment]
do you see the difference of the `h1` element in the above 2 screenshots?
I'm using OSX Chrome there...

**Comment by bertez** [comment]
Oh, ok I was looking at the subtitle... thanks!
