### ISSUE TITLE
create: holding palette elements should be like picking them up

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#20]
Elements should grow 10% in size compared to previous size (thumbnail size in palette ~or current size in canvas~)

EDIT: only implementing this for palette elements for now

**Comment by bertez** [comment]
It is fairly easy for the palette elements an utterly complicated for the elements already in canvas... define the priority of this issue because it could take more time than expected

**Comment by phivk** [comment]
Ok, let's definitely implement this on the palette elements.
Ill split 'growth of canvas elements on hold' into a separate issue 👌
