### ISSUE TITLE
create 1: implement bg image of canvas

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#25]
Today @matopysny will redesign bg image of canvas in step 1 and how it responds to being hovered with a figure to signify the figure can be dropped in the area.

**Comment by bertez** [comment]
Try to give it some air or the borders because there is no pixel perfection on the web

**Comment by matopysny** [comment]
This would work well?

https://drive.google.com/drive/folders/0B0LkX_BiOf9xbVg3NmNoUk1ndEk

**Comment by phillchill** [comment]
looks ok to me 👌

**Comment by phivk** [comment]
the shape looks good to me 👌 

@matopysny so you mean: 
1. initial state: small
2. on figure drag hover over canvas: big

?

I would like to differentiate 3 states:
1. initial state: small & light color
2. on figure hold over palette: small & dark color
3. on figure drag hover over canvas: big & dark color
