### ISSUE TITLE
create3: horizontal flip should be triggered by double click (not single click).

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#28]
horizontal flip should be triggered by double click (not single click).
~holding a fig/obj should bring it to front (on top of all other elements).~

EDIT: broken out 'bring to front' into separate issue: #43

**Comment by bertez** [comment]
I forgot to tell you the second one will be so complicated because of unexpected interactions between the dragdrop library and the way things work with css.

I'll try again, but I cannot promise anything. 😞

**Comment by phivk** [comment]
ok, I'm breaking 'bring element to front' out into a separate issue #43
