### ISSUE TITLE
save: Ability to type special characters and capitalized letters

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#29]
Email addresses may include special characters and significant upper&lower case characters.

This may be fixed by secondary keyboard mode for special characters (like on mobile phone onscreen keyboards)? 

ref: the username part of the email address is case sensitive (https://www.lifewire.com/are-email-addresses-case-sensitive-1171111)

**Comment by bertez** [comment]
I can add the special characters valid on email and upper and lower case, including more characters or combinations it's very complicated, a lot of time. I propose to stick to a simplified keyboard.

**Comment by phivk** [comment]
I'm wondering: are there email addresses that can't be input without:
- special chars
- capitals
?

Perhaps we can simplify by:
- choosing not supporting capitalization (because most email hosts treat userName and username the same.
- choosing a small subset of most used characters in email. 

for ref: this seems to be the full set of legal chars: https://stackoverflow.com/a/2049510/1465222

**Comment by bertez** [comment]
I think I can do that with capitalization
