### ISSUE TITLE
gallery: should navigate to home screen after 20 second inactivity timeout

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#37]
inactivity timeout should be shown in circle around 'home icon'

![screen shot 2017-08-23 at 14 19 21](https://user-images.githubusercontent.com/902958/29615390-15d93610-880e-11e7-8c32-6e956700a590.png)

**Comment by bertez** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/arc
