### ISSUE TITLE
gallery: on thumbnail click, thumbnail size should animate into modal size

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#38]
thumbnails should 'grow' into modal size on open and modal should shrink into thumbnail size on close

**Comment by bertez** [comment]
This kind of animation could be dangerous at this point... I'll try to do something creative but maybe growing up to become a different set of elements is a big deal.

**Comment by phivk** [comment]
ok, I was being (perhaps a bit too) creative here 😊 

It would be good to have something else than just 'hard appear'. It could also be a fade, I guess that would simplify a lot?

**Comment by bertez** [comment]
same issue #15
