### ISSUE TITLE
gallery: palette in modal should list the titles of source artworks used in composition

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#41]
![6-gallerydetail](https://user-images.githubusercontent.com/902958/29617027-a83a552a-8813-11e7-9e84-cba633e73f02.png)

per element, source artwork should be defined as:
- title
- url (not used in touch screen mode, only in online gallery on website)

@phillchill can specify title and url as attributes, e.g. in `parts.json`

**Comment by bertez** [comment]
So it must have an scroll, isn't it?

**Comment by phivk** [comment]
unfortunately there will be cases where there is more items to show than fit on that area, i.e. when a user included elements from many different source artworks.

I see 3 options:
1. scroll
2. paging
3. only showing as many items as can fit (at the 1920 x 1080 touch screen resolution), and still using scroll to accomodate this view on smaller screens (laptops / desktops)

I'm quite in favor of option 3, but option 1 would be a good first step.
