### ISSUE TITLE
create 3: figure out a way to bring element to front (in front of all other elements)

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#43]
broken out into separate issue from #28 :
> holding a fig/obj should bring it to front (on top of all other elements).

@bertez :
> I forgot to tell you the second one will be so complicated because of unexpected interactions between the dragdrop library and the way things work with css.
> I'll try again, but I cannot promise anything. 😞

**Comment by bertez** [comment]
I'M BATMAN 🦇
