### ISSUE TITLE
Welcome Screen: Slovak and English buttons

### ISSUE THREAD

**Issue by matopysny** [unfoldcollective/Apprentice-of-Okolicne#44]
@bertez please find "welcome screen.sketch" file (you can copy size and locations of buttons) and  SVGs for Slovak and English buttons.

https://drive.google.com/drive/folders/0B0LkX_BiOf9xakItYlVFODdsX00

**Comment by phivk** [comment]
Sorry @matopysny, we can't use flags for this

http://www.flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/

Please use "English" and "Slovenčina" or "EN" and "SK"

**Comment by matopysny** [comment]
@bertez @phillchill I made "SK" and "EN". Please find them on this link:

https://drive.google.com/drive/folders/0B0LkX_BiOf9xakItYlVFODdsX00

**Comment by bertez** [comment]
Do I need to use svg? the buttons are pretty simple and definetely easy to create with CSS

**Comment by bertez** [comment]
merged into #9

**Comment by phivk** [comment]
For the record, styling the buttons with CSS is actually preferred 👍
