### ISSUE TITLE
Palette: Buttons Proportions

### ISSUE THREAD

**Issue by matopysny** [unfoldcollective/Apprentice-of-Okolicne#46]
@bertez @phillchill Could you take a look at buttons, please? The icons onto the button cycles are bit smaller. Confirm icon onto a button is not optically centered. Could you move it a bit lower? Please find closer description here:

https://drive.google.com/drive/folders/0B0LkX_BiOf9xRENHQ3BPWUFmbEk

**Comment by bertez** [comment]
I'll try my best to stick to the design, and of course these buttons can be adjusted better, but in general there is no pixel perfection on the web so there will be always a difference between browsers, computers even the default installed fonts sometimes make small rendering differences.

Anyway, no problem 👍

**Comment by phillchill** [comment]
@bertez I imagined we'd do the video timeline in HTML, but now see that @matopysny has 'burned' it into the video, which might actually be nice and easy (considering we are hiding all controls).
OK to stick with timeline burned into the video as in the current videos?
