### ISSUE TITLE
welcome: text is still too bold

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#49]
@matopysny are you sure the font on welcome screen is Maiola Bold? Your design looks much lighter than the Maiola Bold webfont that Berto is using...

@matopysny can you also review the font weight on the other screen and give feedback here for @bertez ?

**Comment by bertez** [comment]
The difference is minimal because we only have the bold version of Maiola, not the other versions.

**Comment by bertez** [comment]
So, the only solution is getting the regular version of the font, am I right? What's the next step?

**Comment by phivk** [comment]
@matopysny can you please comment?

**Comment by matopysny** [comment]
@bertez @phillchill could you try to use these two fonts for welcome screen, please?

regular:

http://www.fontpalace.com/font-download/MaiolaPro/

italic:

http://freakfonts.com/fonts/maiola-pro-italic.html

thank you.

**Comment by bertez** [comment]
I prefer to use fonts ready for the web, these are not, we have to convert them and I had bad experiences in the past... I reduced the weight of the main title: would this be ok for you?

![screen shot 2017-09-05 at 17 19 05](https://user-images.githubusercontent.com/159838/30068531-604d66a8-925e-11e7-8bf1-44ab17dbf42c.png)

**Comment by phivk** [comment]
this looks better to me 👍 
I know the gallery will probably buy the proper Regular webfont soon so we can update to that later.

We can stick with this for now.

@bertez can you also apply that font-weight reduction to text on all other screens please?

**Comment by bertez** [comment]
the font weight can be decreased from bolder to bold, not from bolder to normal 😞 

I close this to keep the list clean, just fire me an issue when you got the new font.

**Comment by phivk** [comment]
> the font weight can be decreased from bolder to bold, not from bolder to normal 😞

that's ok

can you apply the same reduction "from bolder to bold" to all other texts?

**Comment by bertez** [comment]
I do not think there are any more bolder texts, only the h1
