### ISSUE TITLE
save & gallery & composition view: implement redesigned composition titles

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#56]
we figured out that the current way of titling the compositions ({initial} from {town}) leads to problems in Slovak, because {town} should be inflected (e.g. Amsterdam -> Amsterdamu)

We are not going to solve that thorny i18n grammar issue automatically in the app, so here's a new idea: 
- the user just signs with their name (no hometown), e.g. "Philo"
- the artwork is simply titled by the user's initial, e.g. "P"

this way we still stay close to the exhibition and catalogue design:
![screen shot 2017-08-31 at 11 17 29](https://user-images.githubusercontent.com/902958/29916200-5e3d25b6-8e3e-11e7-93ea-808b1ff24d9d.png)

this will affect the following screens:
1. [ ] save: only ask for Name and Email Address (not hometown)
2. [ ] gallery: We need a redesign for the gallery thumbnails that incorporates the user's initial and it should signify that the thumbnail is clickable to open it in full screen (like the current zoom icon)
3. [ ] composition view: the title in top right simply becomes the initial, e.g. "P"

@matopysny can you please work on a redesign for '2. gallery' and link to the designs here on this Github issue?

**Comment by matopysny** [comment]
I'm working on it. So there will be just one letter.

**Comment by phivk** [comment]
@matopysny correct, the initial is only one letter

**Comment by matopysny** [comment]
please find redesign of the gallery "5-Gallery2.png" and "6-GalleryDetail2.png" here: 

https://drive.google.com/drive/folders/0B0LkX_BiOf9xQ3pPOTNHa0pnLUE

**Comment by phivk** [comment]
Thanks @matopysny , looks great! 

Do you think the 'zoom icon' is necessary? I think that the round look of the initial in the circle hints at being clickable... what do you think?

**Comment by matopysny** [comment]
I agree that user would already know that everything rounded is clickable. I don't think it is necessary. I just wanted to be as clear as possible. I think we don't need to have zoom icon in the thumbnails. Please find "5-Gallery3.png" in here:

https://drive.google.com/drive/folders/0B0LkX_BiOf9xQ3pPOTNHa0pnLUE

**Comment by phivk** [comment]
awesome @matopysny we simplified even more, I love it!

@bertez designs linked in last message above are ready to be implemented

**Comment by bertez** [comment]
no problem about this, but the icon is covering the center of the image, is that not an issue?

**Comment by phivk** [comment]
having the center of the image covered by the initial is no problem, it might even encourage people to click to see the whole image

**Comment by bertez** [comment]
cool!
