### ISSUE TITLE
all screens: disable right click

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#61]
@LuciaDub on slack:
> we will need to somehow turn of the right click and windows finctions as it is very easy for the user to get to the inspector by an accident etc.

**Comment by phivk** [comment]
potential (part of the) solution? not sure if it would also prevent multitouch gestures that we need...
https://stackoverflow.com/a/737043/1465222

**Comment by bertez** [comment]
ok, thanks
