### ISSUE TITLE
create3: the figures tutorial does not show up automatically

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#62]
when the user navigates to create3 screen (figs&objs) the tutorial video for moving, resizing, rotation, etc should play automatically.
video should display identical to video in create1 screen

**Comment by bertez** [comment]
Are you completely sure? The step 3 video is pretty long and the user already know where to get help... In my opinion this could break the interaction process and maybe lose the user attention...

**Comment by phivk** [comment]
I agree that it's long, but that video contains essential info for the user to succesfully create their composition.

I think we could make the 'A-FigureControl' video shorter:
1. cut off first 3 second (users already know drag and drop)
2. leave out moving (everybody knows this too, also because it's essentially the same as drag and drop)
this already saves 5 of 25 seconds...

@matopysny Anything else we can do to the animation to shorten the video?

**Comment by matopysny** [comment]
We can remove drag and drop and moving a figure from the beginning. I can look at the short pauses between every step and make them a bit shorter. It can save maybe a sec.I can take a look also at speed. Maybe it could be a bit faster? I need to try it.

**Comment by matopysny** [comment]
@phillchill @bertez please find the shorter and faster video "A-FigureControl-2.mp4". It has 16 sec. Might be enough?

https://drive.google.com/drive/folders/0B0LkX_BiOf9xLUdEUnEtSDhtLXM
