### ISSUE TITLE
bug: sometimes smaller objects stay selected and keep following your finger

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#63]
@LuciaDub on Slack:
> big issue is with smaller objects, sometimes they get stuck and stay selected and they keep on following your finger, you cannot unselect and neither progress

@LuciaDub can you please describe how this issue can be reproduced? what do you do in order for this to happen? If possible add screenshots please...

**Comment by LuciaDub** [comment]
ah, very hard to identify...it happened for example when manipulating with a sword and broom......when you try to scale it on top of other object, maybe that could be the issue: smaller object is on tom of a bigger object and then you try to scale the smaller one and this happens...but not sure. Richard was also asking about how are the objects defined, he mentioned something about that if they are rectangles, maybe they sometimes overlap and then you select two at once and one of them gets stuck?

**Comment by phivk** [comment]
@LuciaDub can you make a sort screen grap video?

**Comment by bertez** [comment]
yes, the objects are inside rectangular bounding boxes, and what you really drag is the bounding box, no fix for this one sorry

**Comment by bertez** [comment]
is this the same issue as the "two finger drag" one?

**Comment by phivk** [comment]
I think so, but can't be 100% sure...

**Comment by bertez** [comment]
I pushed a possible solution to this bug, it works on my ipad, that's the only touchscreen I have available. Please let me know when you have the opportunity to test it on the gallery touch screen.

@phillchill @LuciaDub

**Comment by phivk** [comment]
@bertez I think this was the earliest report of something related to #106 and shouldn't have been closed. (just saying so we all learn 🙂  )

**Comment by bertez** [comment]
If I remember correctly it was closed after a test on a different computer, probably in lucia's laptop. And it worked.
