### ISSUE TITLE
create3: remove element button should be like design

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#65]
'cross icon' instead of 'red thrash can'

svg elements are here:
https://drive.google.com/drive/folders/0B0LkX_BiOf9xbGdySlhfckdYaHM

**Comment by bertez** [comment]
Using that color will make the dropzone almost unnoticeable over some patterns/exteriors ... should we use a different color / effect?

**Comment by phivk** [comment]
good point @bertez 
what do you think @matopysny ?

**Comment by matopysny** [comment]
The idea was that the icon is instantly blinking while figure is active. I think it is visible enough. If you think it should be more visible I would change color for white

**Comment by matopysny** [comment]
I meant that the icon appears while figure is touched (like in animation) so I suppose this kind of appearing and disappearing (like blinking) could attract enough attention for user. But as I said maybe clear white color would make the job. What do you think?

**Comment by bertez** [comment]
ok, I understand @matopysny, I'll go with the animation, let's see I can do and maybe tomorrow you can review it 👍

**Comment by bertez** [comment]
@matopysny done, let me deploy a development version and you can check it by yourself, it's basically what you show in the video. 💃
