### ISSUE TITLE
Gallery: Keyboard issue: Decimal Numbers instead of Old Style Figures

### ISSUE THREAD

**Issue by matopysny** [unfoldcollective/Apprentice-of-Okolicne#66]
<img width="541" alt="screen shot 2017-08-31 at 12 12 05" src="https://user-images.githubusercontent.com/31274508/29919250-d4749ed0-8e48-11e7-8de3-16e0b7041d0d.png">

I can't see latest changes on the app. Please take a look at the numbers int keyboard and text inputs There should be Decimal Numbers. In Maiola are Oldtyle Figures by default (they are used only with lower cases!). Thank you.

**Comment by matopysny** [comment]
<img width="1099" alt="numbers" src="https://user-images.githubusercontent.com/31274508/29919408-7e92e0fc-8e49-11e7-9090-31f7169a1263.png">

**Comment by bertez** [comment]
hi @matopysny, sadly I do not have those glyphs available on the webfont, we could use another font if you want

http://torinak.com/font/lsfont.html <- check here the glyphs available

**Comment by matopysny** [comment]
Hi Berto, if it is possible could you use numbers from Eczar Semi Bold please? It is available at google fonts (I hope it could work) https://fonts.google.com/?query=Eczar
Sorry for late respond.

**Comment by phivk** [comment]
for the record, this has low priority relative to outstanding bugs and other tweaks
