### ISSUE TITLE
timeout animation progresses too slowly and not continuously

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#68]
![screen shot 2017-09-01 at 08 40 32](https://user-images.githubusercontent.com/902958/29958124-65f9b126-8ef1-11e7-94da-9ad360377f6f.png)

it should take (around) 20 seconds for the timeout to complete.

Currently the circle seems to 'shrink a step' every second. Could it instead move smoothly in a continuous way?

**Comment by bertez** [comment]
debug reasons
