### ISSUE TITLE
save: keyboard should use icon instead of CAPS text

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#69]
as in design:
![screen shot 2017-09-03 at 18 44 36](https://user-images.githubusercontent.com/902958/30004941-0c215b48-90d8-11e7-89ae-9a71a4e654a4.png)

@matopysny can you please upload icon to keyboard folder?
https://drive.google.com/drive/folders/0B0LkX_BiOf9xT3ExOW55MnRldjA

**Comment by matopysny** [comment]
@phillchill @bertez please find Cap Button here:
https://drive.google.com/drive/folders/0B0LkX_BiOf9xT3ExOW55MnRldjA

**Comment by matopysny** [comment]
<img width="567" alt="screen shot 2017-09-04 at 20 09 32" src="https://user-images.githubusercontent.com/31274508/30035866-d3b31cd8-91ae-11e7-8b98-1fd037dbbe02.png">

@phillchill @bertez Sorry for late reaction. I used everywhere Maiola Bold. I have no idea why it renders bolder than the design proposal

**Comment by matopysny** [comment]
Would work there 2 PNGs? One for SK and one for EN language?

**Comment by bertez** [comment]
the main title can be lighter, the subtitle is as light as it could be, should I make the title lighter?

**Comment by bertez** [comment]
btw, I think we are commenting on the wrong issue, the right one is this one:

https://github.com/unfoldcollective/Apprentice-of-Okolicne/issues/49

**Comment by matopysny** [comment]
@phillchill @bertez I apologize, wrong channel.
