### ISSUE TITLE
Define help system

### ISSUE THREAD

**Issue by bertez** [unfoldcollective/Apprentice-of-Okolicne#7]
Try to make it simple, if the help system can fit in a div that is visible or hidden. Upload here the final design, please.

Deps:
- #8

**Comment by phivk** [comment]
working on the definition via: https://zpl.io/agjXZOV

**Comment by phivk** [comment]
UX is as specified in the above zeplin link.
Graphic design in this screen:
https://drive.google.com/file/d/0B0LkX_BiOf9xZGJmYXdJN05ka3c/view?usp=drivesdk
