### ISSUE TITLE
composition view: pallete layout should reflect design

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#71]
text elements are slightly different than design because of Title + Intitution, but overal it should stick to:
* text size
* text alignment
* padding

![screen shot 2017-09-03 at 18 56 03](https://user-images.githubusercontent.com/902958/30005021-e32bf7d2-90d9-11e7-9c04-92671d4f9e46.png)

**Comment by bertez** [comment]
Ok!
