### ISSUE TITLE
Display loading state after user hits save

### ISSUE THREAD

**Issue by bertez** [unfoldcollective/Apprentice-of-Okolicne#72]
We need:

- [x] A design
- [ ] Modify the code to show the button when is saving

**Comment by matopysny** [comment]
@bertez @phillchill Please find details about loading spinner here:

https://drive.google.com/drive/folders/0B0LkX_BiOf9xemZQbEtmSzlNekU

Thanks

**Comment by phivk** [comment]
@matopysny I agree with the discussion about not putting overlay on overlay.
I like the design above 👍 
@bertez can we go with this spinner approach?
