### ISSUE TITLE
The keyboard is missing hyphen and underscore characters "-", "_"

### ISSUE THREAD

**Issue by LuciaDub** [unfoldcollective/Apprentice-of-Okolicne#73]
Many people might have this character as part of their email addresses, can we incorporate it into the keyboard?

**Comment by bertez** [comment]
Sure!

**Comment by matopysny** [comment]
A1: yes It is clear: to tap instead of to hold a fig/obj.
A2: I can do it tonight at least around (wed) 02:00

Q: Repo means: upload it directly to the Git hub source? Could you send me a link, please?

**Comment by matopysny** [comment]
sorry wrong channel
