### ISSUE TITLE
save dialog doesnt use i18nized language string

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#74]
![screen shot 2017-09-05 at 10 48 28](https://user-images.githubusercontent.com/902958/30053045-c8fddca0-9227-11e7-809f-bf2bdad34742.png)

probably due to this line in SaveDialog.jsx:
https://github.com/unfoldcollective/Apprentice-of-Okolicne/blob/87af9baf6463df79db1d6d6a1311246ed1444cd4/front/app/js/components/Create/SaveDialog/SaveDialog.jsx#L81

**Comment by bertez** [comment]
👍
