### ISSUE TITLE
Figures getting unsharp when scaled down

### ISSUE THREAD

**Issue by LuciaDub** [unfoldcollective/Apprentice-of-Okolicne#79]
![img_2918](https://user-images.githubusercontent.com/11088934/30060049-f9afef36-9241-11e7-9d14-96d5096c5966.JPG)
![img_2919](https://user-images.githubusercontent.com/11088934/30060050-f9b221d4-9241-11e7-99c6-c597f2b752df.JPG)

**Comment by bertez** [comment]
😄 

Well, this is absolutely normal, as you can see clearly in the picture there is not enough **phisical pixels** on the area of the image to render a more sharp picture. 

1920x1080 resolution is not that sharp, specially when you are close to the screen.
