### ISSUE TITLE
Implement help system

### ISSUE THREAD

**Issue by bertez** [unfoldcollective/Apprentice-of-Okolicne#8]

**Comment by bertez** [comment]
@phillchill @matopysny sorry I cannot find the videos for the help system... can you remind me where they are?

**Comment by matopysny** [comment]
@bertez @phillchill you can download videos from Google Drive:

https://drive.google.com/drive/folders/0B0LkX_BiOf9xLUdEUnEtSDhtLXM

Please note, I'm updating both explanations videos. I will have them ready around 04.00 AM.

**Comment by bertez** [comment]
thanks @matopysny !

**Comment by matopysny** [comment]
@bertez @phillchill Plese find updated videos "A-DragAndDrop.mp4" and "A-FigureControl.mp4" here:

https://drive.google.com/drive/folders/0B0LkX_BiOf9xLUdEUnEtSDhtLXM

**Comment by phivk** [comment]
@bertez I imagined we'd do the video timeline in HTML, but now see that @matopysny has 'burned' it into the video, which might actually be nice and easy (considering we are hiding all controls).
OK to stick with timeline burned into the video as in the current videos?

**Comment by bertez** [comment]
Yes please
