### ISSUE TITLE
Disabling of browser pinch zooming (Chrome)

### ISSUE THREAD

**Issue by LuciaDub** [unfoldcollective/Apprentice-of-Okolicne#80]
https://drive.google.com/file/d/0B5GguBgdeuZ_bzAzNTEtOEdMTzg/view

**Comment by phivk** [comment]
@bertez as the video above shows, the pinch zoom issue is not fixed by 
https://github.com/unfoldcollective/Apprentice-of-Okolicne/commit/87af9baf6463df79db1d6d6a1311246ed1444cd4

This is currently priority number 1.

**Comment by bertez** [comment]
I will look into it but maybe is not an option anymore

**Comment by bertez** [comment]
I pushed a few changes using:

https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

which should work on chrome, but it does not work on IOS so I have not the hardware to test, so if you could test this on a touchscreen it would be great.

**Comment by phivk** [comment]
testing now...

**Comment by phivk** [comment]
OMG IT WORKS ON LUCIA'S TOUCH MONITOR! 🎉 🎉 🎉 

will confirm tomorrow by testing on the real touch screen...

**Comment by bertez** [comment]
can you scroll on the gallery and other scroll elements?

**Comment by phivk** [comment]
yes, scrolling works on the gallery 👍

**Comment by bertez** [comment]
I pass the issue to you until you check with the touchscreen

**Comment by phivk** [comment]
works as it should on the touch screen 👍
