### ISSUE TITLE
figs/objs animation should show 'bring to front' by TAP instead of HOLD

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#82]
- [x] update animation ( @matopysny )
- [ ] replace video in repo ( @phillchill )

@matopysny can you make a small update to the figs/objs animation to show **tap** instead of **hold** to bring figure to front?

If you upload it to drive, Ill replace it in the repo

**Comment by matopysny** [comment]
A1: yes It is clear: to tap instead of to hold a fig/obj.
A2: I can do it tonight at least around (wed) 02:00

**Comment by matopysny** [comment]
@phillchill please find updated animation "A-FigureControl-3.mp4" here:

https://drive.google.com/drive/folders/0B0LkX_BiOf9xLUdEUnEtSDhtLXM

Thank you
