### ISSUE TITLE
welcome: slow video load (from gallery or on lang switch) makes text unreadable for a while

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#87]
The bg video on the welcome screen takes a fraction to load, during that time the text is displayed on the background with the same color, making it unreadable.

see screengrab: https://drive.google.com/open?id=0BxirWWTjJsE7Y01HNVV2NjFMZms

hypothetical solutions:

1. load video faster (not sure if possible, @bertez ?)
2. set the background to display a picture of the golden brocade pattern
3. set background-color of welcome screen to darker color, so that text is readable. I propose a color close to the average of the bg video, e.g. #614D27. What do you think @matopysny ?
4. combination of 2 and 3

**Comment by phivk** [comment]
for option 2, I imagine a 1920x1080 version of this image:
![screen shot 2017-09-06 at 14 33 03](https://user-images.githubusercontent.com/902958/30112162-989997f4-9310-11e7-849b-daf8379b889c.png)

@bertez would option 2 that have any effect; I mean, would it be the case that the image is loaded before the video (I'm talking on language switching, not on first page load)

**Comment by matopysny** [comment]
@phillchill I like both options 2 and 3. If the solid color #614D27 would load faster I would go with that. If it doesn't 't matter I would try solution 3. (I would consider if that possible blink [different grade of shade] would not be too confusing)
