### ISSUE TITLE
a composition doesn't show thumbnail in gallery

### ISSUE THREAD

**Issue by phivk** [unfoldcollective/Apprentice-of-Okolicne#96]
![screen shot 2017-09-07 at 15 28 30](https://user-images.githubusercontent.com/902958/30165957-286c61c8-93e2-11e7-9fea-6756b203d47b.png)

todo:
- [x] remove problematic composition
- [ ] prevent future problems by this bug

**Comment by bertez** [comment]
I cannot reproduce the thumnail bug, neither I find anything on the logs... I don't know, maybe a network problem??

**Comment by bertez** [comment]
closing this, if anything happens in the future open it again

**Comment by phivk** [comment]
👌  maybe due to network
